#ifndef _PORT_DEFS_
#define _PORT_DEFS_

#define DRIVE_LEFT_FRONT 15
#define DRIVE_LEFT_BACK 14
#define DRIVE_RIGHT_FRONT 16
#define DRIVE_RIGHT_BACK 12
#define PUNCHER_MOTOR 11
#define PUNCHER_ANGLE 13
#define BALL_INTAKE 17
#define VISION_PORT 19
#define CAP_ARM 20

#define LIMITSWITCH_PORT 'A'

#endif
